# Generated by Django 5.0.2 on 2024-03-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
